### PR TITLE
Regexr and ! support. Term with + - bugfix

### PR DESCRIPTION
**Pull request by dpesch2**
- Support for Lucene 4.x regular expression search formatted as /regexpr/.  
- Support for ! operator that is just a shorthand for NOT. 
- Fixed bug with term containing with + - inside. According the lucene grammar terms could contains such characters inside term. They are prohibited only at the beginning of the term where they are interpreted as operators.

### CODE REVIEW

**Comment by thoward** [comment]
Hi Daniel!

I just merged in another set of changes from ZenDesk which has some overlap w/ this. Do you mind updating the PR against those changes? 

I think their changes did not include the `!` operator, regexes, or support for the latest PEG.js, so there's a lot of value in this PR that would be nice to merge in.

After that, I'll wrap this up and publish a new version to npm.

Thanks,
Troy

**Comment by dpesch2** [comment]
Hi Troy
Thanks for response. I will rebase my changes so it could be merged and released to npm.
Best Regards
Daniel

**Comment by whitelynx** [comment]
@dpesch2 Any chance of this getting rebased?

**Comment by thoward** [comment]
Closing this per PR #18 by @HeGanjie, which includes the portions of this PR that did not conflict with master.

**Pull request closed without merging**
